export { default as ArrowSvg } from './icons/arrow.svg?component'
export { default as CartSvg } from './icons/cart.svg?component'
export { default as CartInButtonSvg } from './icons/cartInButton.svg?component'
export { default as AvatarSvg } from './icons/avatar.svg?component'
export { default as ComparisonSvg } from './icons/comparison.svg?component'
export { default as CrossSvg } from './icons/cross.svg?component'
export { default as FavouriteSvg } from './icons/favourites.svg?component'
export { default as HomeSvg } from './icons/home.svg?component'
export { default as TrashSvg } from './icons/trash.svg?component'
export { default as ShareSvg } from './icons/share.svg?component'
// export { default as BriefcaseSvg } from './briefcase.svg?component'
// export { default as DeliverySvg } from './delivery.svg?component'
// export { default as LogoutMobileSvg } from './logoutMobile.svg?component'
// export { default as ProductsSvg } from './products.svg?component'
// export { default as SmileSvg } from './smile.svg?component'
// export { default as WorkerSvg } from './worker.svg?component'
